### ISSUE TITLE
Webhook for Non Whatsapp Mobile Number and Message failure

### ISSUE THREAD

**Issue by JavakarBits** [aldinokemal/go-whatsapp-web-multidevice#106]
unable to identify the Non Whatsapp mobile number and message got failure.
We need webhook for Non Whatsapp mobile number after message submitted.

**Comment by aldinokemal** [comment]
But you can use GET '/user/info' to make sure the device exists before sending the message.

**Comment by aldinokemal** [comment]
<img width="626" alt="Screenshot 2024-03-04 at 08 50 00" src="https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/14232125/4ca6deac-1327-4e04-8d8d-c26e1e0b418b">


In versions >= 4.9.5, this function will be applied automatically before sending a message. This means that it will check to see if the user is already on WhatsApp before sending, and if they aren't, it will throw an error.
