### ISSUE TITLE
multidevice

### ISSUE THREAD

**Issue by ezequieltomazini** [aldinokemal/go-whatsapp-web-multidevice#108]
How do I use the API to connect more than one device, is it possible?

**Comment by JavakarBits** [comment]
using docker, you can setup with different port number for each device

**Comment by aldinokemal** [comment]
> using docker, you can setup with different port number for each device

Yes, you can use a different port. If you want to learn how to change the port for a docker app or native app, read the documentation (readme.md).

**Comment by paginare** [comment]
How to automate this process?
