### ISSUE TITLE
maximum send message

### ISSUE THREAD

**Issue by DobbyAkhmadi** [aldinokemal/go-whatsapp-web-multidevice#111]
do you have any clue for maximum blast a message using this lib for getting unbanned? i'ts okay when i add a delay 2-3 sec for send a message to different number.? any idea?

**Comment by aldinokemal** [comment]
I think WhatsApp also has a limit on how many contacts can be sent every day. You should also think about this, along with how many texts you send every second.

**Comment by DobbyAkhmadi** [comment]
if i have wa business account , can it automatically increase limit msg per day? maybe more than basic user

**Comment by aldinokemal** [comment]
not really sure unless you use the official WhatsApp API or official WhatsApp account, because there is no clear documentation for that.

**Comment by aldinokemal** [comment]
you can move to [discussions](https://github.com/aldinokemal/go-whatsapp-web-multidevice/discussions) instead of issues for next question
