### ISSUE TITLE
`forwarded` field not being correctly populated in the webhook message

### ISSUE THREAD

**Issue by traysh** [aldinokemal/go-whatsapp-web-multidevice#114]
I read `forwarded` is supposed to be set to `true` on the webhook payload when the received message was forwarded, but its value is always null to me.

The debug output even contains `contextInfo:{forwardingScore:1 isForwarded:true}`, but that doesn't get propagated to the webhook payload.

**Comment by aldinokemal** [comment]
can you attach here your webhook payload here?

**Comment by traysh** [comment]
Sure, here it is:
```
{
  "audio": null,
  "contact": null,
  "document": null,
  "forwarded": null,
  "from": "REMOVED:16@s.whatsapp.net in REMOVED@s.whatsapp.net",
  "image": null,
  "list": null,
  "live_location": null,
  "location": null,
  "message": {
    "id": "REMOVED",
    "text": "Muita coragem",
    "replied_id": ""
  },
  "order": null,
  "pushname": "REMOVED",
  "quoted_message": null,
  "reaction": {
    "id": "",
    "message": ""
  },
  "sticker": null,
  "video": null,
  "view_once": null
}
```

The associated debug log is:
```
[Main INFO] Received message REMOVED from REMOVED:16@s.whatsapp.net in REMOVED@s.whatsapp.net
(pushname: REMOVED, timestamp: 2024-02-11 REMOVED +0000 UTC, type: text): extendedTextMessage:{
text:"Muita coragem" contextInfo:{forwardingScore:1 isForwarded:true} inviteLinkGroupTypeV2:DEFAULT}
messageContextInfo:{deviceListMetadata:{senderKeyHash:"REMOVED" senderTimestamp:REMOVED
senderAccountType:E2EE receiverAccountType:E2EE recipientKeyHash:"REMOVED" recipientTimestamp:REMOVED}
deviceListMetadataVersion:2}
```

**Comment by aldinokemal** [comment]
Thanks for your report, it's already fixed here:
https://github.com/aldinokemal/go-whatsapp-web-multidevice/commit/1c900043cb97eb31c7cadbdbd79b4f8aba1cf2b5

you can retry in v4.9.3
<img width="521" alt="Screenshot 2024-02-12 at 05 52 42" src="https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/14232125/f809bca4-ee94-4af6-95aa-ccc92177a8c2">
