### ISSUE TITLE
Not Connect

### ISSUE THREAD

**Issue by WilmarAlmeida** [aldinokemal/go-whatsapp-web-multidevice#116]
Not Connect. 

Even using refresh it doesn't connect

![WhatsApp Image 2024-02-28 at 14 49 25](https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/54598182/6cb8aed1-d1fa-48b4-bf95-f0256a02bfba)

I using the lastest version 4.9.4

**Comment by aldinokemal** [comment]
I just tried, and there is no issue on my end. Have you checked using another phone?

**Comment by WilmarAlmeida** [comment]
Sorry... I try in anonimal mode and works... Thanks and congratulations.
