### ISSUE TITLE
🐞 How get token basic auth for api?

### ISSUE THREAD

**Issue by jenilutfifauzi** [aldinokemal/go-whatsapp-web-multidevice#122]
### What happened?

How get token basic auth for api?

### Reproduction Steps

```bash
1. create auth user
2. get device by api
```

### Application Version

4.11.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by aldinokemal** [comment]
This is not a bug. You can move to discussion; 

It's a normal basic authentication. you just need to add header `Authorization` basic Header with a B64 User and Password

**Comment by jenilutfifauzi** [comment]
please example request authorization on api

**Comment by RuanAyram** [comment]
curl -X 'GET' 'http://localhost:3005/app/login' -H 'accept: application/json' -H 'Authorization: Basic Base64 user:password encoded'
