### ISSUE TITLE
🐞 Reply message by ID does not work

### ISSUE THREAD

**Issue by drksbr** [aldinokemal/go-whatsapp-web-multidevice#128]
### What happened?

Using the front-end, I can't reply to a message, whether privately or in a group.

### Reproduction Steps

```bash
1. using front-end send message modal
2. set group-id
3. set msg id
4. set message
5. send message
6. the message is sent to the group or contact, but not as a reply.
```

### Application Version

v4.12.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by aldinokemal** [comment]
Hi @drksbr , thanks for reporting this bug
I have fixed in https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/129

**Comment by aldinokemal** [comment]
just info that this feature have limitation that haven't fixed yet https://github.com/aldinokemal/go-whatsapp-web-multidevice/issues/86
