### ISSUE TITLE
🐞 Tried to send a couple hundred messages to different recepients, WhatsApp logged me out and go-whatsapp-web-multidevice erased my paired phone from store.

### ISSUE THREAD

**Issue by HaimenToshi** [aldinokemal/go-whatsapp-web-multidevice#134]
### What happened?

As per title. Tried sending an assignment to my students (149 in total) through the server using HTTP and NodeJS, the WhatsApp app on my phone logged me out because "You've logged in using a different phone". Checking on the server web UI, I've found that my paired phone got erased completely as if I didn't pair it to begin with. What could be the issue ?

### Reproduction Steps

```bash
Send a lot of messages at once
```

### Application Version

v4.12.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by HaimenToshi** [comment]
> since this is not officially an API. send hundreds of messages at once is extremely not recommended.   You can create round-robin mechanisms with your app to avoid crashes or being banned from WhatsApp.

Is it common that this server crashes under load ? And how common are WhatsaApp bans for this kind of usage ? Thank you.

**Comment by aldinokemal** [comment]
Yes, this is a common issue.We don't know how many limit messages are safe for us since there is no clear statement from WhatsApp about that.

**Comment by HaimenToshi** [comment]
> Yes, this is a common issue.We don't know how many limit messages are safe for us since there is no clear statement from WhatsApp about that.

I'll implement a queue that sends a message every 10 - 15 seconds. From your experience would that be good enough ?

**Comment by aldinokemal** [comment]
I can't guarantee about that, seem better move this to discussion

**Comment by HaimenToshi** [comment]
Hello. Message queue is implemented, it will send a message every 8 seconds. I'll test this today at work and report what I find. Thank you so much.

**Comment by lairhas** [comment]
@HaimenToshi this has something to do with the behavior of the program and how it send the message. Avoid sending tons of message to random numbers in short period of time. But still, no one can guarantee WhatsApp will not ban your number no matter how since this is "unofficial".

**Comment by aldinokemal** [comment]
for further discussion please move to discussion tab
