### ISSUE TITLE
⚡️  Ability to use standalone binary without installing libraries (feature flags)

### ISSUE THREAD

**Issue by sayyidyofa** [aldinokemal/go-whatsapp-web-multidevice#135]
### What problem does your feature request solve?

Currently, The program will immediately crash if libvip or ffmpeg is not installed, even if the user does not need the image/video capability

With this feature, The user can run the program without installing additional libraries

### Describe the solution you are proposing.

A feature flag in the parameters of the program, if the user want to incluse image/video capabilities

### Importance

Could Live Without

### Additional Context

- [ ] This missing feature presents as a bug.
- [ ] This missing feature is forcing me to consider alternatives.

**Comment by aldinokemal** [comment]
Good idea, will available on next release
currently still under development https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/136
