### ISSUE TITLE
⚡️ [Feature Request] - Add new device using code alongside qrcode

### ISSUE THREAD

**Issue by baharsah** [aldinokemal/go-whatsapp-web-multidevice#137]
### What problem does your feature request solve?

![image](https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/69349170/43c88e28-f736-45b6-822b-dbea3468db1a)
![image](https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/69349170/a4eea787-440f-440d-b643-6d4be5a5912d)

### Describe the solution you are proposing.

for device which is can't open a camera e.g. emulator, can use it for login schema

### Importance

I Need It

### Additional Context

- [ ] This missing feature presents as a bug.
- [ ] This missing feature is forcing me to consider alternatives.

**Comment by baharsah** [comment]
the reference https://pkg.go.dev/go.mau.fi/whatsmeow#Client.PairPhone

**Comment by aldinokemal** [comment]
@baharsah https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/171
