### ISSUE TITLE
⚡️ Delete message just for me

### ISSUE THREAD

**Issue by fgonga** [aldinokemal/go-whatsapp-web-multidevice#138]
### What problem does your feature request solve?

Currently, if you try to delete the message it will be deleted for everyone, it would be interesting to delete the message just for me.

Our WhatsApp is used by internal employees and also sends sensitive information to my client.

We would like it if the message was sent to be deleted just for me.

It could be something like delete -> /message/{id}

I am available to contribute financially for this feature.

### Describe the solution you are proposing.

Nothing to add

### Importance

I Need It

### Additional Context

- [ ] This missing feature presents as a bug.
- [X] This missing feature is forcing me to consider alternatives.

**Comment by aldinokemal** [comment]
It is possible
just tested in local and worked

**Comment by fgonga** [comment]
Okay, so should we wait for the update?

**Comment by aldinokemal** [comment]
https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/153
