### ISSUE TITLE
🐞 How to scan multi whatsapp account

### ISSUE THREAD

**Issue by pandiarajanvp** [aldinokemal/go-whatsapp-web-multidevice#144]
### What happened?

How can i add more devices?

### Reproduction Steps

```bash
1. scan multi-WhatsApp account in http://localhost:3000/app/login
its show as {"code":"ALREADY_LOGGED_IN","message":"you already logged in :)"}
```

### Application Version

4.13.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by w3nder** [comment]
It's not a problem, Api is single instance.

**Comment by aldinokemal** [comment]
Please read another issue or discussion to prevent duplication. https://github.com/aldinokemal/go-whatsapp-web-multidevice/issues/108
