### ISSUE TITLE
Multi Account Support⚡️ 

### ISSUE THREAD

**Issue by berkbirkan** [aldinokemal/go-whatsapp-web-multidevice#147]
### What problem does your feature request solve?

Multi account support

### Describe the solution you are proposing.

Hello. First of all, thank you for your efforts. I really like your API, especially the web interface is very well thought out. However, I couldn't find a feature for adding or removing multiple accounts. Since your API's name includes "multidevice," I thought this feature was included, but I guess I was mistaken. If you could add this feature, I would be very happy. I'm sure many others would feel the same way because running each account on different ports is not very efficient.

### Importance

I Need It

### Additional Context

- [ ] This missing feature presents as a bug.
- [ ] This missing feature is forcing me to consider alternatives.

**Comment by aldinokemal** [comment]
Multi-device here means that in WhatsApp multi-device architecture. Eventough this base library supports multi-account login. I personally do not implement this because of the of the webhook issue, and we can also able to run on another port easily if you want to login with a different account.
