### ISSUE TITLE
📖 REST API documentation consistency improvements

### ISSUE THREAD

**Issue by alexvuka1** [aldinokemal/go-whatsapp-web-multidevice#148]
### What happened?

I have identified the following possible instances of inconsistencies between [Open API specification](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/7292058718a0441cfa75bb05b8ff0475999e1acc/docs/openapi.yaml) and [Documentation](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/7292058718a0441cfa75bb05b8ff0475999e1acc/readme.md):

- ### 🟩Found in Open API specification, 🟥Not found in Documentation
	- [ ] [`GET /app/devices`](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/7292058718a0441cfa75bb05b8ff0475999e1acc/docs/openapi.yaml)
	- [ ] [`POST /message/{message_id}/reaction`](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/7292058718a0441cfa75bb05b8ff0475999e1acc/docs/openapi.yaml)
- ### 🟥Not found in Open API specification, 🟩Found in Documentation
	- [ ] [`POST /message/:message_id/react`](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/7292058718a0441cfa75bb05b8ff0475999e1acc/readme.md?plain=1#L118)
	- [ ] [`DELETE /group/participants`](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/7292058718a0441cfa75bb05b8ff0475999e1acc/readme.md?plain=1#L124)
	- [ ] [`POST /group/participants/promote`](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/7292058718a0441cfa75bb05b8ff0475999e1acc/readme.md?plain=1#L125)
	- [ ] [`POST /group/participants/demote`](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/7292058718a0441cfa75bb05b8ff0475999e1acc/readme.md?plain=1#L126)

**About**

This is part of the evaluation of my Master's Project at Imperial College London. The section above is automatically generated and aims to expose API documentation inconsistencies in real-world GitHub repositories. The end goal is for the tool to be used as part of CI/CD, namely as a GitHub action. 

Hopefully, this is a step towards easier maintenance of API documentation. If you find this helpful, please consider updating the documentation to keep it in sync with the source code. I am also happy to assist with it, if appropriate. If this has not been useful, consider updating this issue with an explanation, so I can improve my approach. Thank you!

### Application Version

4.13.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by aldinokemal** [comment]
@alexvuka1 I think you can check in Readme that promote, demote, etc. haven't been released yet.

**Comment by alexvuka1** [comment]
Thank you for the prompt response and for pointing out the false positives. 

The tool currently flags any discrepancies between the documented endpoints and the Open API specification to ensure consistency. However, I realise this can include endpoints that are pending release, such as in your case. To improve the tool's accuracy, it would be useful to incorporate a way to identify and exclude such pre-release features from the checks. 

Another approach that I can think of is to add the endpoints to the Open API specification but mark them as not implemented. That would also resolve the inconsistencies. It would be interesting to hear your thoughts on that.

Other than that, it flagged 3 more inconsistencies, are those valid?

Thank you again for your cooperation and understanding!
