### ISSUE TITLE
⚡️ Login Username And password

### ISSUE THREAD

**Issue by justinthoms** [aldinokemal/go-whatsapp-web-multidevice#161]
### What problem does your feature request solve?

![image](https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/57831354/8fce4fa4-5431-4c57-b1a3-05ba97016d26)
 this is verry essay to access need to add an security username and password protection

### Describe the solution you are proposing.

 this is verry essay to access need to add an security username and password protection

### Describe alternatives you have considered.

 this is verry essay to access need to add an security username and password protection

### Importance

Nice to Have

### Additional Context

- [X] This missing feature presents as a bug.
- [X] This missing feature is forcing me to consider alternatives.

**Comment by aldinokemal** [comment]
You can use basih auth for protect this `--basic-auth=username:password`
