### ISSUE TITLE
⚡️  [Feature Request] - Remove Participant in Group

### ISSUE THREAD

**Issue by AmineSoukara** [aldinokemal/go-whatsapp-web-multidevice#168]
### What problem does your feature request solve?

.

### Describe the solution you are proposing.

.

### Describe alternatives you have considered.

Hi, Could you please add the feature to remove participants from groups, It would greatly help with group management.

### Importance

I Need It

### Additional Context

- [ ] This missing feature presents as a bug.
- [X] This missing feature is forcing me to consider alternatives.

**Comment by aldinokemal** [comment]
https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.15.0
