### ISSUE TITLE
⚡️ otomatis tag in group

### ISSUE THREAD

**Issue by MuhammadAlfiFauzul** [aldinokemal/go-whatsapp-web-multidevice#176]
### What problem does your feature request solve?

not automatick tag in group

### Describe the solution you are proposing.

example: hallo @628xxxx , not tag otomatis, just number i need to tag otomatis

### Describe alternatives you have considered.

to make it easier for teams to manage messages

### Importance

I Need It

### Additional Context

- [X] This missing feature presents as a bug.
- [X] This missing feature is forcing me to consider alternatives.

**Comment by aldinokemal** [comment]
Added https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.17.0

**Comment by MuhammadAlfiFauzul** [comment]
masih tidak mau nge tag mas, hanya berbentuk nomor @ nya tidak berfungsi
![Screenshot 2024-08-26 104516](https://github.com/user-attachments/assets/0ab7675d-a553-420a-b2c5-e5b53c6feb54)



> Added https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.17.0

**Comment by MuhammadAlfiFauzul** [comment]
> Added https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.17.0

![image](https://github.com/user-attachments/assets/50e30048-530b-4020-94ec-e7e3cbfed0fc)
saya sudah update ke v17 mas tapi judulnya masih v16, atau judul nya emang belum ganti ya

**Comment by kiratheone** [comment]
Fitur mention harusnya sudah ada di versi @MuhammadAlfiFauzul, cuma sepertinya belum sesuai ekpektasi dari mas @MuhammadAlfiFauzul. Dilihat dari changesnya [v4.17.0]( https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.17.0) hanya update workflow aja

**Comment by MuhammadAlfiFauzul** [comment]
> Added https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.17.0

alhamdulilah sudah solved ternyata tidak bisa tebal, harus huruf biasa sebelumnya saya kasih tebal huruf nya

**Comment by aldinokemal** [comment]
untuk versi nanti saya update ulang

**Comment by MuhammadAlfiFauzul** [comment]
> Fitur mention harusnya sudah ada di versi @MuhammadAlfiFauzul, cuma sepertinya belum sesuai ekpektasi dari mas @MuhammadAlfiFauzul. Dilihat dari changesnya [v4.17.0](https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.17.0) hanya update workflow aja

baik mas ini sudah solved ko, tidak bisa menggunakan bold di huruf mention nya, jadi pas saya ubah biasa langsung bisa
