### ISSUE TITLE
⚡️ [Feature Request] - Extract Participants Numbers From A Group

### ISSUE THREAD

**Issue by AmineSoukara** [aldinokemal/go-whatsapp-web-multidevice#177]
### What problem does your feature request solve?

Hi, Could you please add the feature to Extract numbers from a group, It would greatly help with group management.

### Describe the solution you are proposing.

.

### Importance

I Need It

### Additional Context

- [ ] This missing feature presents as a bug.
- [X] This missing feature is forcing me to consider alternatives.

**Comment by AmineSoukara** [comment]
Or maybe check a number if he is in the target group

**Comment by aldinokemal** [comment]
I think you can you this endpoint `/user/my/groups`

**Comment by AmineSoukara** [comment]
> I think you can you this endpoint `/user/my/groups`

Thanks That Helps 🫡
