### ISSUE TITLE
🐞 websocket exhausted

### ISSUE THREAD

**Issue by dippreneurlab** [aldinokemal/go-whatsapp-web-multidevice#179]
### What happened?

after run the go file

-
 ┌───────────────────────────────────────────────────┐
 │                   Fiber v2.52.4                   │
 │               http://127.0.0.1:3000               │
 │       (bound on host 0.0.0.0 and port 3000)       │
 │                                                   │
 │ Handlers ............ 42  Processes ........... 1 │
 │ Prefork ....... Disabled  PID .............. 6565 │
 └───────────────────────────────────────────────────┘

08:48:58.054 [Client ERROR] Client outdated (405) connect failure (client version: 2.2412.50)
08:48:58.137 [Client/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
^Csignal: interrupt

### Reproduction Steps

```bash
1. logout the account from my mobile
2. restarted the server
```

### Application Version

1.0.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by devabdulharis** [comment]
how to fix ?

**Comment by dippreneurlab** [comment]
reinstall the service

**Comment by peektoseen** [comment]
This error still exist.
For me - it happen every time after 3 minute 33 seconds:

`$ docker run aldinokemal2104/go-whatsapp-web-multidevice

 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.52.5                   │ 
 │               http://127.0.0.1:3000               │ 
 │       (bound on host 0.0.0.0 and port 3000)       │ 
 │                                                   │ 
 │ Handlers ............ 48  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................. 1 │ 
 └───────────────────────────────────────────────────┘ 

07:54:35.341 [Client/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF


`

**Comment by peektoseen** [comment]
@dippreneurlab , please, reopen this issue.

**Comment by dippreneurlab** [comment]
I think. this issue will occur if the user disconnects it from the phone first instead of the server.

**Comment by peektoseen** [comment]
This happens even without the phone. If you just run the project, the socket will disconnect after 3 minutes 33 seconds.
