### ISSUE TITLE
⚡️ Add a Secret option to Webhook

### ISSUE THREAD

**Issue by LuizEdgar** [aldinokemal/go-whatsapp-web-multidevice#184]
### What problem does your feature request solve?

There is no way to know who is calling my Webhook. 
I want to add a Secret to GoWhatsapp so it sends the secret when calling the Webhook and then I csan verify this was sent by the GoWhatsapp.

### Describe the solution you are proposing.

1. Add a new option like `--webhook-secret=abcdefghijklm12345` 
2. The secret `abcdefghijklm12345` is sent in a Header on the Webhook HTTPs request.
3. I check the `abcdefghijklm12345` on my side.

### Importance

I Need It

### Additional Context

- [ ] This missing feature presents as a bug.
- [X] This missing feature is forcing me to consider alternatives.

**Comment by aldinokemal** [comment]
interesting, will prioritize this

**Comment by sohepalslamat** [comment]
Is there any news about this case? I need to receive messages.

**Comment by aldinokemal** [comment]
https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.18.0

**Comment by LuizEdgar** [comment]
Amazing! Thanks! :)
