### ISSUE TITLE
⚡️ Mention user with '@'

### ISSUE THREAD

**Issue by traysh** [aldinokemal/go-whatsapp-web-multidevice#185]
### What problem does your feature request solve?

It is currently not possible to mention someone with '@'

### Describe the solution you are proposing.

I propose that mentioning is supported

### Describe alternatives you have considered.

An alternative to mentions is replying an user message. It is not the same thing, but it will make the message more visible. But replies are not working correctly, see https://github.com/aldinokemal/go-whatsapp-web-multidevice/issues/173

### Importance

Nice to Have

### Additional Context

- [ ] This missing feature presents as a bug.
- [ ] This missing feature is forcing me to consider alternatives.

**Comment by aldinokemal** [comment]
I believe this feature aleady added recently in https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.17.0

you can use `@<phoneNumber>`

**Comment by traysh** [comment]
Yes it works, I completely missed it. Thank you!

**Comment by traysh** [comment]
Actually, there's a bug preventing it to work on some cases. See https://github.com/aldinokemal/go-whatsapp-web-multidevice/issues/186
