### ISSUE TITLE
🐞 Message is not sent if there's punctuation after a mention

### ISSUE THREAD

**Issue by traysh** [aldinokemal/go-whatsapp-web-multidevice#186]
### What happened?

If there's a dot after a mention, the message is not sent to a whatsapp group. Example: "I'll refer to him as @938372634."

Removing the '.' after the mention makes it work. This can be tested on the web interface.

### Reproduction Steps

```bash
1.open the web interface
2.go to send message
3.change the type to group and enter the required data
4.in the message field, enter: "I'll refer to him as @938372634."
5.send the message
6.the web interface will show a success message, but the message will **not** appear in the conversation
```

### Application Version

4.17.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by traysh** [comment]
Hm, I see the behavior is different on whatsapp web and on the Android client. On whatsapp web, no message is shown. But on the Android client, the message is shown without the mention be translated to the user's name, just  "@938372634."

**Comment by aldinokemal** [comment]
simple, just remove punctuation

**Comment by traysh** [comment]
Yes, that's what I'm doing as a workaround to make it work. But it is a workaround, not a proper fix =)

The image bellow was taken from the android app. As you can see, if a mention is sent from the Android app, it supports adjacent punctuation.

![share_8016674629495697289](https://github.com/user-attachments/assets/cafee195-d492-40c6-b115-f33491d49dba)

Removing punctuation is not the best solution, as it changes the text A text without `.` looks strange <= see?

**Comment by aldinokemal** [comment]
interesting, I'll investigate it

**Comment by aldinokemal** [comment]
https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.18.0

**Comment by traysh** [comment]
Perfect, thank you!
