### ISSUE TITLE
Auto Reply Toggle

### ISSUE THREAD

**Issue by aarzaary** [aldinokemal/go-whatsapp-web-multidevice#19]
Can i set on/off autoreply after running without restart service?

**Comment by aldinokemal** [comment]
currently, this app does not support for that
you can modify to customize it as you want here
https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/main/src/utils/whatsapp.go#L173

**Comment by ary-labs** [comment]
Thanks
I will try 👍
