### ISSUE TITLE
can't sent to group chat "phone: must be a valid E164 number"

### ISSUE THREAD

**Issue by punyahenry** [aldinokemal/go-whatsapp-web-multidevice#2]
curl -X POST -F 'phone=6285xxx-xxxxx@g.us' -F 'message=hi' http://172.17.12.185:3000/send/message

{"code":400,"message":"phone: must be a valid E164 number.","results":null}

**Comment by aldinokemal** [comment]
you just send phone with 628968xxxxxz without @g.us

**Comment by punyahenry** [comment]
curl -X POST -F 'phone=6285xxxx-xxxx' -F 'message=haloo halooo' http://172.17.12.185:3000/send/message
{"code":400,"message":"phone: must be a valid E164 number.","results":null}

already tested and same result

**Comment by aldinokemal** [comment]
could you retry with phone number withoud - charecter
`6285xxxx-xxxx` -> `6285xxxxxxxx`

**Comment by punyahenry** [comment]
sending to group need dash (-) character

**Comment by aldinokemal** [comment]
currently this not support for group
you can edit by forking this repo or waiting for new updates from me

**Comment by aldinokemal** [comment]
Fix on this PR https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/3
