### ISSUE TITLE
🐞 Null returned after message edited

### ISSUE THREAD

**Issue by baharsah** [aldinokemal/go-whatsapp-web-multidevice#219]
### What happened?

Edited message
![image](https://github.com/user-attachments/assets/2eb61fe4-bf40-494a-bdcd-ae1b85af3569)
Edited Callback
![Screenshot from 2024-12-12 20-43-49](https://github.com/user-attachments/assets/63cda99c-50e2-4aef-946d-7588a2b8f8b8)
Original Mesage

![Screenshot from 2024-12-12 20-44-13](https://github.com/user-attachments/assets/d60acdf7-51f5-422d-bd19-64a0a868b88d)

### Reproduction Steps

```bash
-
```

### Application Version

v4.21.0

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by aldinokemal** [comment]
https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/221
