### ISSUE TITLE
message: the length must be between 1 and 50

### ISSUE THREAD

**Issue by punyahenry** [aldinokemal/go-whatsapp-web-multidevice#24]
got error when sending message to personal and group, return json error:
{code: 400, message: "message: the length must be between 1 and 50.", results: null}

it's have limitation on sending message?

**Comment by aldinokemal** [comment]
From WhatsApp, there is no limitation.
I don't want to make this app misused. This limit is mandatory. Maybe I'll increase the maximum characters to 1k for the next update

**Comment by aldinokemal** [comment]
updated here [v3.5.1](https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v3.5.1)
