### ISSUE TITLE
Delivery report/status and chatstate

### ISSUE THREAD

**Issue by punyahenry** [aldinokemal/go-whatsapp-web-multidevice#37]
Hi Aldi

Thanks for apply webhook for incoming message.. And another request  it's posible create other webhook for delivery and chatstate?

**Comment by aldinokemal** [comment]
it's possible to add delivery message webhook
but I don't have any plan for adding this

**Comment by punyahenry** [comment]
delivery report so we can track status message ^_^ and chatstate it's a gimick but nice to have. And for 2 services looks good if separated webhook with incoming message

Thanks..

**Comment by aldinokemal** [comment]
Could you let me know what you wanted with a delivery report in webhook?
You could check your apps to see whether the webhook has been sent.
