### ISSUE TITLE
Multi Account

### ISSUE THREAD

**Issue by aarzaary** [aldinokemal/go-whatsapp-web-multidevice#44]
I'm using auth basic with diffirent user but still same account

**Comment by aldinokemal** [comment]
can you elaborate on how to reproduce this?

**Comment by aarzaary** [comment]
I'm read from [this](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/38ef3ec46821fbd2fd6508b0a3408b68bd0f574e/readme.md?plain=1#L17) that explains able to add multi account
Example:
1. user: a pass: a login using number 6289123456789
2. if user: b pass: b login, it's still login using 6289123456789 not prompted to login with new account 

my argument is
./wa -b=a:a,b:b

Thanks

**Comment by Rikievalin1234** [comment]
This is not a multi-session @aarzaary. It's just multi-basic auth.

**Comment by aarzaary** [comment]
Oh okay @Rikievalin1234 
Waiting response from dev
if it is true, then let this issue be closed

**Comment by aldinokemal** [comment]
Yes correct @Rikievalin1234
It's just multi account for basic auth, however, if we adopted multi session we'll lose we hook feature @aarzaary

**Comment by aarzaary** [comment]
Thank You
