### ISSUE TITLE
Get Media File from Webhook?

### ISSUE THREAD

**Issue by mahmoodmomani** [aldinokemal/go-whatsapp-web-multidevice#50]
how can i get media file from webhook event ?
I only got .ENC file URL
as i see media stored at /storages folder, can i access it by url?

**Comment by aldinokemal** [comment]
Hello bro @mahmoodmomani thanks for raising an issue, Now you can download media via
here is the details PR https://github.com/aldinokemal/go-whatsapp-web-multidevice/issues/50

**Comment by mahmoodmomani** [comment]
Thanks bro !!
can you do samething to sticker?

**Comment by aldinokemal** [comment]
Fixed here https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/54
