### ISSUE TITLE
Receive Replay on message - Webhook 

### ISSUE THREAD

**Issue by mahmoodfakhri** [aldinokemal/go-whatsapp-web-multidevice#53]
When receive replay on message, its sent as null to web hook

**Comment by aldinokemal** [comment]
could you elaborate with attached payload send to webhook?

**Comment by mahmoodmomani** [comment]
in v4.4.4 the app sending 6 blank request to webhook then not sending any request to webhook when message received.
no error on console
i try v4.4.3 webhook working fine

**Comment by aldinokemal** [comment]
It's come from group message or private message?

**Comment by mahmoodmomani** [comment]
private message, all message type no thing work in v4.4.4

**Comment by aldinokemal** [comment]
Hmm, seem I have tested in a private message on every media here https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/54

**Comment by aldinokemal** [comment]
please attache here the webhook payload that was sent in v4.4.3 but not in v4.4.4

**Comment by mahmoodfakhri** [comment]
in V4.4.3
![image](https://user-images.githubusercontent.com/30110760/211018884-b611c24b-152e-4687-a22b-e17fe923b330.png)

**Comment by aldinokemal** [comment]
https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.4.5
You may want to check again to see if the issue has been resolved.
