### ISSUE TITLE
Tags Not Proper in docker

### ISSUE THREAD

**Issue by anshuman852** [aldinokemal/go-whatsapp-web-multidevice#55]
Hi @aldinokemal  thank you for the great work that you are doing
From what i can see on [dockerhub](https://hub.docker.com/r/aldinokemal2104/go-whatsapp-web-multidevice/tags?page=1&ordering=-name) the images arent tagged as per version number 
Thats a concern for me if i am to use it anywhere as i cant just put image:latest 
I would create a pr to fix this issue but i dont think this pipeline is part of this github repo. 
Thanks a lot, Much appreciated

**Comment by aldinokemal** [comment]
Yes, @anshuman852, that's a great idea to release every version. However current docker release hasn't broken the previous version

I'll release it in the docker hub as well as every tag release. I'll notify you whether this completed

**Comment by aldinokemal** [comment]
start today I'll publish latest and tag version as well
https://hub.docker.com/r/aldinokemal2104/go-whatsapp-web-multidevice/tags
