### ISSUE TITLE
Error and Warning

### ISSUE THREAD

**Issue by WilmarAlmeida** [aldinokemal/go-whatsapp-web-multidevice#58]
After a few days with the process stopped, when I go up I get the following logs : 

[WARNING] 2023-01-15T16:19:43-03:00 SessionCipher.go:214 ▶  failed to verify ciphertext MAC: mismatching MAC in signal message
[ERROR] 2023-01-15T16:19:43-03:00 SessionCipher.go:268 ▶  Unable to verify ciphertext mac: mismatching MAC in signal message

**Comment by aldinokemal** [comment]
I have updated the library from whatsmeow in [v4.4.5](https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.4.5), it would be more efficient for you to reach out to the library directly [here](https://github.com/tulir/whatsmeow/issues)

**Comment by brunoaduarte** [comment]
https://github.com/tulir/whatsmeow/issues/58
