### ISSUE TITLE
how to receive the "message_id" displayed in the console (debug = True) in the webhook

### ISSUE THREAD

**Issue by MasamioNakada** [aldinokemal/go-whatsapp-web-multidevice#62]
I receive this json in the body :

`{'audio': None, 'contact': None, 'document': None, 'forwarded': None, 'from': 'phone_number@s.whatsapp.net', 'image': None, 'list': None, 'live_location': None, 'location': None, 'message': 'Hola', 'order': None, 'sticker': None, 'video': None, 'view_once': None}`

Debug Console : 
`<ack class="message" id="3A3F4B1D50958E3AA641" to="phone_number@s.whatsapp.net"/>
14:06:44.680 [Main INFO] Received message 3A3F4B1D50958E3AA641 from phone_number@s.whatsapp.net (pushname: Cohete, timestamp: 2023-02-16 14:06:44 -0500 -05): conversation:"Hola" messageContextInfo:{deviceListMetadata:{senderKeyHash:"1\xe7;6\xb9mʮ\xcf|" senderTimestamp:1676363087 recipientKeyHash:"D怿{)To\xd0$" recipientTimestamp:1676524241} deviceListMetadataVersion:2}`

**Comment by aldinokemal** [comment]
Great idea! I had forgotten to include the message_id in the webhook. I'll let you know once I have completed that.

**Comment by aldinokemal** [comment]
updated here [v4.5.1](https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.5.1)
