### ISSUE TITLE
Error on recieving images/files

### ISSUE THREAD

**Issue by WhiteAbyss** [aldinokemal/go-whatsapp-web-multidevice#68]
time="2023-03-26T22:23:41+05:00" level=error msg="Failed to send webhoookFailed to download document: open statics/media/1679851421-45d4888d-4779-43bc-acb9-5b1c2543d505.jfif: The system cannot find the path specified."

Is it supposed to download file from whatsapp server, but trying to get it from invalid link?

**Comment by aldinokemal** [comment]
It appears that the file either does not exist or could not be downloaded. Is this an issue with all files?

**Comment by WhiteAbyss** [comment]
I tried to send images (png) and files (zip, pdf).

**Comment by aldinokemal** [comment]
I have reproduce this issue and not happen to me, here is my webhook details:

- I have sent image, and webhook sent `path of images`
<img width="755" alt="Screenshot 2023-04-06 at 08 15 52" src="https://user-images.githubusercontent.com/14232125/230248238-434ba1a5-a414-47c8-99c3-1e56f265876d.png">

- I open the image with `full url` and it's working
<img width="1129" alt="Screenshot 2023-04-06 at 08 17 00" src="https://user-images.githubusercontent.com/14232125/230248358-59144dde-c3bd-4ed4-bdda-16e399050b1a.png">

**Comment by aldinokemal** [comment]
and this is another sample (send PDF document)

<img width="801" alt="Screenshot 2023-04-06 at 08 21 01" src="https://user-images.githubusercontent.com/14232125/230248837-d187cfbe-cd00-45c4-b1be-e3bc6f627bb5.png">
<img width="1402" alt="Screenshot 2023-04-06 at 08 21 13" src="https://user-images.githubusercontent.com/14232125/230248879-48e550ec-9463-468b-9866-a5aa5da860e5.png">

**Comment by WhiteAbyss** [comment]
I'll try run it on docker, maybe this is only windows problem
