### ISSUE TITLE
Invalid QR code

### ISSUE THREAD

**Issue by CesarCort** [aldinokemal/go-whatsapp-web-multidevice#73]
Hi! I'm trying to use QR code generation to log in to my device, but WhatsApp is responding with "Invalid QR Code." I have tried it on three different devices.

Any ideas? This issue just started today.

![Imagen de WhatsApp 2023-06-08 a las 11 05 16](https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/52660278/d847d617-373e-45ac-a26d-d9c9989924ca)

**Comment by aldinokemal** [comment]
The newest version, v4.7.1, is now available for use and functions properly. It has been tested on both Android and iOS 16 platforms.
