### ISSUE TITLE
Inclusion of Reaction and Reply Details in Webhook JSON Payload

### ISSUE THREAD

**Issue by alexhawke** [aldinokemal/go-whatsapp-web-multidevice#76]
Hi aldinokemal,

I am currently facing an issue with the webhook data when reacting or replying to a message. It appears the generated webhook payload doesn't include any specific information about these actions.

The below JSON payload was generated when I reacted to a message:

`{
  "audio":null,
  "contact":null,
  "document":null,
  "forwarded":null,
  "from":"447123456789.0:5@s.whatsapp.net in 447123456789@s.whatsapp.net",
  "image":null,
  "list":null,
  "live_location":null,
  "location":null,
  "message":"",
  "message_id":"3EC0X32142E5221CA4C26F",
  "order":null,
  "sticker":null,
  "video":null,
  "view_once":null
}`

Would it be possible to incorporate reaction/reply data in the payload (ideally referencing the original message_id)?

Thanks!

**Comment by aldinokemal** [comment]
Sure, it's will be fixed in v4.7.3

<img width="492" alt="Screenshot 2023-07-23 at 21 24 34" src="https://github.com/aldinokemal/go-whatsapp-web-multidevice/assets/14232125/6129a878-2a08-4923-b24a-d487d42cfbfe">

**Comment by alexhawke** [comment]
Thank you for this, would it also be possible to add something like "reaction_message_id" so that it's possible to know which message is being reacted to?
