### ISSUE TITLE
how to use multi devices ?

### ISSUE THREAD

**Issue by jatinsne** [aldinokemal/go-whatsapp-web-multidevice#77]

**Comment by aldinokemal** [comment]
If you mean, multi-devices are multiple login accounts. You must open this program twice in separate ports. The title whatsapp-web-multidevice refers to WhatsApp's new architecture, which allows us to login into various devices up to four.

I developed apps for multi-device login. However, this app is available to the public at https://kirimwa.me.

**Comment by jatinsne** [comment]
Website 502 gateway error

**Comment by aldinokemal** [comment]
It's accessible, but we're still working on it.

**Comment by jatinsne** [comment]
Can you add buttons api

**Comment by aldinokemal** [comment]
what do you mean buttons api?

**Comment by jatinsne** [comment]
Feature to send whatsapp buttons cta?

**Comment by aldinokemal** [comment]
it's different topic anymore, i will close this
you can create another one
