### ISSUE TITLE
How to use webhook in docker?

### ISSUE THREAD

**Issue by jatinsne** [aldinokemal/go-whatsapp-web-multidevice#79]
configure webhook in docker instance?

**Comment by aldinokemal** [comment]
You can use this command

```bash
docker run --detach --publish=3000:3000 --name=whatsapp --restart=always --volume=$(docker volume create --name=whatsapp):/app/storages aldinokemal2104/go-whatsapp-web-multidevice --webhook="http://yourwebhook.site/handler"
```

**Comment by amanasmuei** [comment]
could you please provide information on the parameters that are passed to the webhook?

**Comment by aldinokemal** [comment]
@amanasmuei you can find it here
https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/456658faf9078cb169481247906d1a95b6dcdc1c/src/pkg/whatsapp/whatsapp.go#L292-L310

**Comment by brianandhikap** [comment]
i was try 
docker run --detach --publish=3000:3000 --name=whatsapp1 --restart=always --volume=$(docker volume create --name=whatsapp1):/app/storages aldinokemal2104/go-whatsapp-web-multidevice --basic-auth=user:user --os=BiyanWABot --debug true --webhook="http://web.site/handler" 

Cannot GET /handler
