### ISSUE TITLE
incorrect link

### ISSUE THREAD

**Issue by alfajrimutawadhi** [aldinokemal/go-whatsapp-web-multidevice#80]
there was a wrong link when cloning repository in readme

**Comment by Itay-Sharoni** [comment]
simply add .git to the end of it

**Comment by alfajrimutawadhi** [comment]
> simply add .git to the end of it

not only that, there's a "-" in the word "multi-device" that shouldn't exist.
maybe can add simple bash script just for installation for make it easier
