### ISSUE TITLE
Webhook "message" attribute is empty when sending from WhatsApp Web

### ISSUE THREAD

**Issue by Itay-Sharoni** [aldinokemal/go-whatsapp-web-multidevice#81]
when using webhook (lets call it Bot)
if a user send a message to the Bot, then the webhook post:
{
  "audio": null,
  "contact": null,
  "document": null,
  "forwarded": null,
  **"from": "97254555555@s.whatsapp.net",**
  "image": null,
  "list": null,
  "live_location": null,
  "location": null,
  **"message": "This is a Test!!",**
  "message_id": "A91DB2EDE7D5B5DBEE63034A96B0A13D",
  "order": null,
  "sticker": null,
  "video": null,
  "view_once": null
}
this is good since i sent "This is a Test!!"

however, now same user send the exact same message but now he uses his WhatsApp Web on his PC
this time there are 2 differences, the "from" attribute look different and message attribute is empty this way

so end-users who interact with the bot must use their phone app instead the PC/ Web App
{
  "audio": null,
  "contact": null,
  "document": null,
  "forwarded": null,
  **"from": "97254555555.0:12@s.whatsapp.net in 97254555555@s.whatsapp.net",**
  "image": null,
  "list": null,
  "live_location": null,
  "location": null,
  **"message": ""**,
  "message_id": "C9C4663CA1BEB301A3",
  "order": null,
  "sticker": null,
  "video": null,
  "view_once": null
}

**Comment by Itay-Sharoni** [comment]
another thing i noticed when i started with --debug

when a user send a message to the phone configured with go-whatsapp
if the end-user used his phone (android in this example) it looks like this (notice my text "Lala" it is in attribute "conversation") :

14:42:51.216 [Main INFO] Received message 0A3CB12A413152CFA0C9FEF694D1EDDB from 97254555555@s.whatsapp.net (pushname: Itay Sharoni, timestamp: 2023-07-04 14:42:51 +0000 UTC, type: text): conversation:"Lala"  messageContextInfo:{deviceListMetadata:{senderKeyHash:"\xa9\x82\xad\xa0?\xd9\tK\x88\x01"  senderTimestamp:1687936453  recipientKeyHash:"V\x98\xd78,kа҅"  recipientTimestamp:1688474298}  deviceListMetadataVersion:2}


but if the same end-user used WhatsApp Web or App for PC it looks like this (notice my text "aasdsd" it is in attribute "extendedTextMessage" and inside that the text is in "text") :

14:42:06.533 [Main INFO] Received message FBBCD294856935C0C4 from 97254555555.0:12@s.whatsapp.net in 97254555555@s.whatsapp.net (pushname: Itay Sharoni, timestamp: 2023-07-04 14:42:06 +0000 UTC, type: text): extendedTextMessage:{text:"aasdsd"  contextInfo:{expiration:0  ephemeralSettingTimestamp:0  disappearingMode:{initiator:CHANGED_IN_CHAT}}}  messageContextInfo:{deviceListMetadata:{senderKeyHash:"\xa9\x82\xad\xa0?\xd9\tK\x88\x01"  senderTimestamp:1687936453  recipientKeyHash:"V\x98\xd78,kа҅"  recipientTimestamp:1688474298}  deviceListMetadataVersion:2}


it looks like WhatsApp did some change on their side, and go-whatsapp need to be updated to capture both for webhook use?

**Comment by aldinokemal** [comment]
@Itay-Sharoni I've verified that upgrading to the newest version is functional, so go ahead.
