### ISSUE TITLE
[Feature Request] Webhook is sent only if message was sent directly to the number with go-whatsapp-web-multidevice

### ISSUE THREAD

**Issue by Itay-Sharoni** [aldinokemal/go-whatsapp-web-multidevice#83]
When using webhook,
currently is will POST to webhook server only if message was sent from: go-whatsapp-web-multidevice or to the number of: go-whatsapp-web-multidevice

but if it is a member of a whatsapp group, and if someone sent a message to the group it will not POST to webhook

ideally, a setting to control if webhook should POST on every message (even if go-whatsapp-web-multidevice  is not the recipient (but it is a member of the group)

example:
go-whatsapp-web-multidevice = 9721111111@s.whatsapp.net
user A = 972222222@s.whatsapp.net
TEST Group = 4545556565656@g.us (both are member of this group)

1. User A > message > go-whatsapp-web-multidevice | webhook will POST ok
2. go-whatsapp-web-multidevice > message > User A | webhook will POST ok
3. User A > message > TEST Group ( not a reply or a tag) | webhook will not POST (not ok)
4. User A > message > TEST Group ( reply to go-whatsapp-web-multidevice ) | webhook will not POST (not ok)
5. User A > message > TEST Group ( tagging go-whatsapp-web-multidevice ) | webhook will not POST (not ok)

i need a way to communicate with go-whatsapp-web-multidevice in groups as well

Thank You!

**Comment by aldinokemal** [comment]
Already added webhook from group chat in [v4.7.3](https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.7.3)
