### ISSUE TITLE
Reaction to message is not working

### ISSUE THREAD

**Issue by Itay-Sharoni** [aldinokemal/go-whatsapp-web-multidevice#85]
When reacting to a message, this only work if this is a message from myself, any other message cannot be reacted
tested with version 4.7.3
and i get error:

`Aug 13 23:54:09 test whatsapp50[104432]: 23:54:09.761 [Client/Send DEBUG] <message id="3EB0F4F1E5D6E248379D" to="972544444444@s.whatsapp.net" type="reaction"><participants><to jid="972544444444.0:0@s.whatsapp.net"><enc decrypt-fail="hide" type="msg" v="2"></enc></to><to jid="972544444444.0:12@s.whatsapp.net"><enc decrypt-fail="hide" type="msg" v="2"></enc></to><to jid="972544444444.0:13@s.whatsapp.net"><enc decrypt-fail="hide" type="pkmsg" v="2"></enc></to><to jid="972544445555.0:0@s.whatsapp.net"><enc decrypt-fail="hide" type="msg" v="2"></enc></to></participants><device-identity></device-identity></message>
Aug 13 23:54:09 test whatsapp50[104432]: 23:54:09.836 [Client/Recv DEBUG] <ack class="message" from="972544444444@s.whatsapp.net" id="3EB0F4F1E5D6E248379D" t="1691960049"/>
Aug 13 23:54:09 test whatsapp50[104432]: 23:54:09 | 200 |    93ms |    172.16.10.47 | POST    | /message/3EB09E3518B07BDEAF8C/reaction`

**Comment by aldinokemal** [comment]
can you check using latest version, and make sure you just react with icon not text
