### ISSUE TITLE
[Feature Request] interactive message

### ISSUE THREAD

**Issue by DobbyAkhmadi** [aldinokemal/go-whatsapp-web-multidevice#88]
can i request a interactive message ? thank you

**Comment by aldinokemal** [comment]
What exactly do you mean by interactive message?

**Comment by DobbyAkhmadi** [comment]
like a whatsapp business add some product menu

**Comment by mandud** [comment]
I'm looking for also this feature.

As per my checking at this time, this feature usually found at WhatsApp bot using NodeJS. 
It can response based on the message that we've defined before.

**Comment by aldinokemal** [comment]
I've just got an info that ButtonMessage only available using whatsapp API (official)
