### ISSUE TITLE
[feature request] Add group's metadata query

### ISSUE THREAD

**Issue by nalakawula** [aldinokemal/go-whatsapp-web-multidevice#9]
To send a message to a group we need group's ID. In my opinion, it is a good idea to add group's metadata query functionality.

Thanks

**Comment by aldinokemal** [comment]
what is group's metadata query? can you explain more detail about this

**Comment by nalakawula** [comment]
I mean a function to get group's metadata (e.g group's id, groups's name, etc). 

PS. I'm not sure if whatsmeow already cover that function or not.

**Comment by aldinokemal** [comment]
oh i see, this feature available in whatsmeow but not implemented yet here

**Comment by nalakawula** [comment]
That sounds great, thanks @aldinokemal !

**Comment by aldinokemal** [comment]
https://github.com/aldinokemal/go-whatsapp-web-multidevice/pull/10
