### ISSUE TITLE
Outgoing Message Webhook

### ISSUE THREAD

**Issue by hazhayder** [aldinokemal/go-whatsapp-web-multidevice#91]
Hi, 
I am wondering if it is possible to receive outgoing messages on webhook using this tool?

**Comment by aldinokemal** [comment]
Certainly it is feasible, but what is the function of this function?

**Comment by hazhayder** [comment]
Use Case 1: (For which we need) 
We have a public number in our organization and an agent handling that we then have a team how would like to examine all the messages received we now want whatever the agent is sending we should be able to see that as well in the tool so to receive it via webhook

**Comment by aldinokemal** [comment]
Sorry, currently I have no plan to include this feature.
