### ISSUE TITLE
Image webhook doesnt have caption

### ISSUE THREAD

**Issue by anshuman852** [aldinokemal/go-whatsapp-web-multidevice#93]
Hi, thanks a lot for your hardwork on this project, i was tinkering with the webhooks and noticed that, the webhook payload doesnt have the caption of the image/video. 
Would be great if you could take a look at this.

**Comment by aldinokemal** [comment]
you can use ver >= https://github.com/aldinokemal/go-whatsapp-web-multidevice/releases/tag/v4.8.0
