### ISSUE TITLE
build undefined error

### ISSUE THREAD

**Issue by miloira** [aldinokemal/go-whatsapp-web-multidevice#97]
`go build main.go`
```
# github.com/h2non/bimg
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:93:49: undefined: Gravity
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:133:29: undefined: Watermark
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:139:34: undefined: WatermarkImage
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:152:26: undefined: Angle
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:181:31: undefined: Interpretation
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:202:27: undefined: Options
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:212:29: undefined: ImageMetadata
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:218:35: undefined: Interpretation
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:234:25: undefined: ImageSize
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\resize.go:11:27: undefined: Options
..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\resize.go:11:27: too many errors
```

**Comment by aldinokemal** [comment]
> `go build main.go`
> 
> ```
> # github.com/h2non/bimg
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:93:49: undefined: Gravity
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:133:29: undefined: Watermark
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:139:34: undefined: WatermarkImage
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:152:26: undefined: Angle
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:181:31: undefined: Interpretation
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:202:27: undefined: Options
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:212:29: undefined: ImageMetadata
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:218:35: undefined: Interpretation
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\image.go:234:25: undefined: ImageSize
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\resize.go:11:27: undefined: Options
> ..\..\..\go\pkg\mod\github.com\h2non\bimg@v1.1.9\resize.go:11:27: too many errors
> ```

I believe you have like missconfig in yourn windows golang that make installation failed
